### ISSUE TITLE
Dark Mode By Default for Single Page

### ISSUE THREAD

**Issue by Lord0fBytes** [casualwriter/casual-markdown-page#1]
I am just wondering if there is a way to default a single page the always be the `darkmode` in the webpage. 
For example I am using `website.com/index.html?file=newpage.md` and I would like to know how to load it to dark mode by default without needing to press the Alt+K buttons.

**Comment by casualwriter** [comment]
sure. for all pages, please modify index.html, add the following style in header
~~~
<style>
body, pre, code { background:#333!important; color:#ccc!important } 
#header, a {background:#555;} th, tr:nth-child(even) {color:#333}
</style>
~~~

for individual markdown file, please add style in frontmatter.  e.g. index.md

~~~
-----------------------------------------------------------------------------
title   : Casual-Markdown 
style   : body, pre, code { background:#333!important; color:#ccc!important }  #header, a {background:#555;} th, tr:nth-child(even) {color:#333}
~~~

feel free to let me know if have any problem.
