### ISSUE TITLE
Remote File Inclusion

### ISSUE THREAD

**Issue by pfeifferch** [casualwriter/casual-markdown-page#2]
Remote File Inclusion

Remote File Inclusion With Remote File Inclusion (RFI for short), attackers can also integrate remote files that are located on other servers. So it is of course very easy to smuggle in your own code. 

What creates file inclusion vulnerabilities? 

File inclusion security gaps arise when unfiltered variables that may contain user input are passed to the include functions mentioned. 

casual-markdown parser
Has great potential, but is unfortunately susceptible to RFI and LFI. Appropriate filters ( ../ // ) should still be installed) 

Demo:
https://casualwriter.github.io/casual-markdown/?file=https://raw.githubusercontent.com/PfeifferchsForks/casual-markdown-page/rfi-demo/source/rfi-demo.md
and
https://casualwriter.github.io/casual-markdown/?file=//raw.githubusercontent.com/PfeifferchsForks/casual-markdown-page/rfi-demo/source/rfi-demo.md

Unfortunately, my JS knowledge is not sufficient to prepare a pull request with modified code :/

**Comment by casualwriter** [comment]
yes.  it includes the casual-markdown.js as below (described in readme.md)
~~~
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/casualwriter/casual-markdown/dist/casual-markdown.css">
<script src="https://cdn.jsdelivr.net/gh/casualwriter/casual-markdown/dist/casual-markdown.js"></script>
~~~

You may use "all-in-one" version, totally self-sufficient.  source: [index-one.html](https://github.com/casualwriter/casual-markdown-page/blob/main/source/index-one.html)

simple use the link of https://casualwriter.github.io/casual-markdown/index-one.html

for example.

https://casualwriter.github.io/casual-markdown/index-one.html?file=https://raw.githubusercontent.com/PfeifferchsForks/casual-markdown-page/rfi-demo/source/rfi-demo.md
